'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { ArrowRightIcon } from '@heroicons/react/24/outline'

const API_BASE = process.env.NEXT_PUBLIC_API_URL

export default function CheckoutButton({ total, disabled }) {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const getToken = () => {
    if (typeof window === 'undefined') return null
    return localStorage.getItem('token')
  }

  const redirectToPayU = (checkout) => {
    // ✅ Create form and submit to PayU
    const form = document.createElement('form')
    form.method = 'POST'
    form.action = checkout.paymentUrl

    // Do not change surl/furl here: they are included in the hash generated by the backend.
    for (const [name, value] of Object.entries(checkout.fields)) {
      const input = document.createElement('input')
      input.type = 'hidden'
      input.name = name
      input.value = value
      form.appendChild(input)
    }

    // Save orderId locally before redirect
    localStorage.setItem('currentOrderId', checkout.orderId)
    localStorage.setItem('paymentId', checkout.paymentId)

    document.body.appendChild(form)
    form.submit()
  }

  const handleCheckout = async () => {
    if (!getToken()) {
      alert('Please login to checkout')
      router.push('/login')
      return
    }

    setLoading(true)
    setError('')

    try {
      // ✅ POST /api/orders/checkout
      const response = await fetch(`${API_BASE}/orders/checkout`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${getToken()}`
        }
      })

      if (response.ok) {
        const data = await response.json()
        // ✅ Redirect to PayU
        redirectToPayU(data)
      } else {
        const err = await response.text()
        setError(err || 'Failed to initiate checkout')
      }
    } catch (error) {
      setError('Network error. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="w-full">
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded-lg text-sm mb-3">
          {error}
        </div>
      )}
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleCheckout}
        disabled={loading || disabled}
        className={`w-full py-4 rounded-xl font-semibold text-base transition-all duration-300 flex items-center justify-center gap-2 ${
          loading || disabled
            ? 'bg-gray-400 cursor-not-allowed text-gray-600'
            : 'bg-[#391F10] text-white hover:bg-[#2a1509] hover:shadow-xl'
        }`}
      >
        {loading ? (
          <>
            <span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
            Processing...
          </>
        ) : (
          <>
            Pay Now
            <ArrowRightIcon className="h-5 w-5" />
          </>
        )}
      </motion.button>
    </div>
  )
}
